name: todo
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.3.8
  flutter_local_notifications: ^8.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: 2.2.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.jpeg"
flutter:
  uses-material-design: true


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  assets:
    - assets/images/person.jpeg
    - assets/images/task.svg
